/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as ProjectProjectIdSlideSlideIdRouteImport } from './routes/project/$projectId/slide/$slideId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdSlideSlideIdRoute =
  ProjectProjectIdSlideSlideIdRouteImport.update({
    id: '/slide/$slideId',
    path: '/slide/$slideId',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/slide/$slideId': typeof ProjectProjectIdSlideSlideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/slide/$slideId': typeof ProjectProjectIdSlideSlideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/slide/$slideId': typeof ProjectProjectIdSlideSlideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/project/$projectId'
    | '/project/$projectId/'
    | '/project/$projectId/slide/$slideId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/project/$projectId' | '/project/$projectId/slide/$slideId'
  id:
    | '__root__'
    | '/'
    | '/project/$projectId'
    | '/project/$projectId/'
    | '/project/$projectId/slide/$slideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/slide/$slideId': {
      id: '/project/$projectId/slide/$slideId'
      path: '/slide/$slideId'
      fullPath: '/project/$projectId/slide/$slideId'
      preLoaderRoute: typeof ProjectProjectIdSlideSlideIdRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ProjectProjectIdSlideSlideIdRoute: typeof ProjectProjectIdSlideSlideIdRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ProjectProjectIdSlideSlideIdRoute: ProjectProjectIdSlideSlideIdRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
